### ISSUE TITLE
How to move funnytweet from validateTweet(); into T.post

### ISSUE THREAD

**Issue by selimsaukkomaa** [selimsaukkomaa/funnytweeter#2]
T.post accepts variables but funnytweet, the variable that is created by the validateTweet function is not global. T.post does not work from within the function, so how to make funnytweet accessible by T.post?

**Comment by akskos** [comment]
So you'd like to have a variable containing a random tweet that doesn't include @ signs in randomTweet, and then call T.post with that variable? In that case you can for example return funnytweet from validateTweet and assign it to a variable in randomTweet.

```javascript
function randomTweet(err, data, response) {

  var tweets = data;
  var funnytweet = tweets[Math.floor(Math.random()*tweets.length)].text + "  😂 😂 😂 ";
  var validatedTweet = validateTweet(funnytweet, tweets);
  // Call T.post with validatedTweet
}

function validateTweet(funnytweet, tweets) {
  if (funnytweet.includes("@")) {
     var funnytweet = tweets[Math.floor(Math.random()*tweets.length)].text + "  😂 😂 😂 ";
     console.log("tweet was discarded");
     validateTweet(funnytweet, tweets);
  } else {
     console.log("found a tweet: " + funnytweet);
     return funnytweet;
  }
}
```

**Comment by selimsaukkomaa** [comment]
Hmm. I don't think this solved my issue, although I think I didn't do a great job explaining it either. I don't really care where the tweet variable is located as such, I just want to somehow make T.post have access to it. I liked your idea of returning the validatedTweet to randomTweet but we're back to square one after that. T.post is not (as far as I understand (which is not much)) a function so I guess it can't be called or variables cannot be passed to it? Earlier I tried placing the entire T.post from the bottom of the code inside validateTweet so it would have access to funnytweet but it wouldn't do anything. 

Anyway, here's the code I tried just now:

```

function randomTweet(err, data, response) {

  var tweets = data;
  var funnytweet = tweets[Math.floor(Math.random()*tweets.length)].text + "  😂 😂 😂 ";
  var validatedTweet = validateTweet(funnytweet, tweets);
  T.post(validatedTweet);

}
function validateTweet(funnytweet, tweets) {
  if (funnytweet.includes("@")) {
    var funnytweet = tweets[Math.floor(Math.random()*tweets.length)].text + "  😂 😂 😂 ";
     console.log("tweet was discarded");
     validateTweet(funnytweet, tweets);
    } else {
     console.log("found a tweet: " + funnytweet);
     return validatedTweet;
    }

}

  T.post('statuses/update', validatedTweet, function(err, data, response) {
    console.log(data.text)
  })


```


And what I got back was

```

/Users/selim/Documents/Projects/funnytweeter/app.js:44
  T.post('statuses/update', validatedTweet, function(err, data, response) {
                            ^

ReferenceError: validatedTweet is not defined
    at Object.<anonymous> (/Users/selim/Documents/Projects/funnytweeter/app.js:44:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

```

**Comment by koolestest** [comment]
T.post is a function and can be called with the validatedTweet variable. The problem in the code now is that when we call T.post (on line 44) it fails because validatedTweet isn't defined in the same (global) scope. The other T.post call (inside randomTweet) is never called because randomTweet is never called. And if it would be called it would fail too because it doesn't pass enough parameters. You can find documentation for it in the npm package page: https://www.npmjs.com/package/twit 

I think the main problem in here is that randomTweet is never called and nothing is fetching (or creating?) the data needed to pass to randomTweet. Based on randomTweet's parameters I'd guess you've intended it to be a callback to some function? Once randomTweet is called with the data that it requires, T.post could be for example called from inside of it with the chosen random tweet.

**Comment by akskos** [comment]
T.post is a function and can be called with the validatedTweet variable. The problem in the code now is that when we call T.post (on line 44) it fails because validatedTweet isn't defined in the same (global) scope. The other T.post call (inside randomTweet) would fail too if the execution would get that far because it doesn't get enough parameters. You can find documentation for it in the npm package page: https://www.npmjs.com/package/twit

**Comment by selimsaukkomaa** [comment]
I got it working! Oh wow, the solution was actually super easy in the end. So I decided to revert back to the original code before the validatedTweet and took a long, hard look at the commented out test tweet code you can see in app.js. on row 44. Turns out the solution was looking more closely at the Twit documentation (or my own code for that matter) all along. I had missed curly braces and the word status from the arguments that I passed to T.post! I had previously gotten them right in the test tweet, but I guess I was thrown off since I was looking at T.post code and not the var testtweet code where I declare the testtweet variable to have those Twit specifications in it. So in the end I ended up with this: 


```

T.get('statuses/user_timeline', params, randomTweet);


function randomTweet(err, data, response) {

  var tweets = data;
  var funnytweet = tweets[Math.floor(Math.random()*tweets.length)].text + "  😂 😂 😂 ";
  validateTweet(funnytweet, tweets);

}
function validateTweet(funnytweet, tweets) {
  if (funnytweet.includes("@")) {
    var funnytweet = tweets[Math.floor(Math.random()*tweets.length)].text + "  😂 😂 😂 ";
     console.log("tweet was discarded");
     validateTweet(funnytweet, tweets);
    } else {
     console.log("found a tweet: " + funnytweet);
    T.post('statuses/update', { status: funnytweet } , callBack);

    }

}

  function callBack(err, data, response) {
    console.log("Posted to Twitter: " + data.text)
  }


```

And it works beautifully now, just perfect. Thanks for the engaging conversation and letting me know that T.post in fact is a function and I just hadn't called it correctly. Awesome job!
